project:
  type: website

website:
  title: "Teaching Material"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Resources"
        menu:
          - href: about.qmd
            text: "Introducing CMI-PB Data"
          - href: about.qmd
            text: "Pertussis Background"
          - href: about.qmd
            text: "Pertussis Timeline"
          - href: about.qmd
            text: "Modeling with CMI-PB data"
          - href: about.qmd
            text: "Prediction challange"

    right:
      - href: about.qmd
        text: CMI-PB
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



